app/urls.py
from django.contrib import admin
from django.urls import path
from app import views

app_name='ytdownloader'

urlpatterns = [
   path('',views.index,name='home'),
   path('donations/',views.donations,name='donations'),
   path('contact/',views.contact,name='contact'),
   path('download/',views.download,name='download'),
   path('download/<resolution>/',views.ytud_download,name='finish'),
]

ytud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import SettingsReference, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
] 

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from pytube import YouTube
import os
from django.core.mail import send_mail
from django.conf import settings


def index(request):
    return render(request,"index.html")

def contact(request):
    if request.method=="POST":
        subject= request.POST["subject"]
        message= request.POST["message"]+"\nEl usuario que envio la consulta es: "+request.POST["email"]
        email_from = settings.EMAIL_HOST_USER
        recipient_list=["adm_ytud@hotmail.com"]
        send_mail(subject,message,email_from,recipient_list)        
        return render(request,"thanks.html")
    
    return render(request,"contact.html")


def donations(request):
    return render(request,"donations.html")

def download (request):
    global url
    url = request.GET.get('url')
    yt = YouTube(url)
    video=[]
    video = yt.streams.filter(progressive=True).all()
    audio = []
    audio = yt.streams.filter(only_audio=True , subtype="mp4")
    print(audio)
    embed_link = url.replace('watch?v=','embed/')
    context = {'audio':audio,'video':video,'embed':embed_link}
    return render(request,"download.html",context)

def ytud_download(request,resolution):
    global url
    homedir = os.path.expanduser("~")
    dirs = homedir + '/Downloads'
    if request.method== 'POST':
        YouTube(url).streams.get_by_resolution(resolution).download(dirs)
        return render(request,'finish.html')
    else: 
        return render(request,'error.html')

app/templates/contact.html
{% extends "generic.html" %}

{% load static %}

{% block content %}

<!-- Contact Form -->
<div class="container my-4">
	<form action="/contact/" method="POST"> {% csrf_token %}
		<div class="form-group">
			<label for="exampleFormControlInput1">Asunto</label>
			<input name="subject" type="text" class="my-1 form-control" placeholder="Ingrese el asunto">
		</div>
		<div class="form-group">
			<label for="exampleFormControlInput1">Email</label>
			<input name="email" type="email" class="my-1 form-control" placeholder="Ingrese su email">
			</div>
		<div class="form-group">
			<label for="exampleFormControlTextarea1">Mensaje</label>
			<textarea name="message" class="my-1 form-control" id="exampleFormControlTextarea1" rows="4" placeholder="Ingrese su mensaje"></textarea>
		</div>
		<div class="form-group mt-3">
			<input type="submit" value="Enviar" class="btn btn-outline-success">
		</div>			
		</form>
</div>

<!-- End --> 
 
{% endblock %}

app/templates/donations.html
{% extends "generic.html" %}

{% load static %}

{% block content %}


<div class="container text-center">
	<img class="rounded mx-auto d-block my-5" src="https://i.imgur.com/EtkRvZy.png" height="200px">
	<p class="mx-auto">Por el momento no acepto donaciones, sin embargo aprecio la intención.</p>
</div>

 
{% endblock %}

app/templates/download.html
<!-- Main Content Start -->

	<div class="container d-flex">
		<iframe class="mx-auto my-5" width="560" height="315" src={{embed}} title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<div class="container">
		<table class="table table-hover table-striped">
			<thead class="bg-dark text-white">
			  <tr>
				<th scope="col">Tipo</th>
				<th scope="col">Calidad</th>
				<th scope="col">Formato</th>
				<th scope="col">Descargar</th>
			  </tr>
			</thead>
			{% for i in video %}
			<tbody>
			  <tr>
				<th>{{i.type}}</th>
				<td>{{i.resolution}}</td>
				<td>{{i.subtype}}</td>
				<td>
					<form action="{% url 'ytdownloader:finish' i.resolution %}" method="post" >
						{% csrf_token %}
						{% if i.resolution == '144p' %}
						<input type="submit" value="Descargar" class="btn btn-outline-success btn-sm" disabled aria-disabled="true">
						{% else %}
						<input type="submit" value="Descargar" class="btn btn-outline-success btn-sm">
						{% endif %}
					</form>
				</td>
			  </tr>
			 </tbody>
			 {% endfor %}
			 {% for i in audio %}
			 <tbody>
			   <tr>
				 <th>{{i.type}}</th>
				 <td>{{i.abr}}</td>
				 <td>mp3</td>
				 <td>
					<form action="{% url 'ytdownloader:finish' i.resolution %}" method="post" >
						<input type="submit" value="Descargar" class="btn btn-outline-success btn-sm" disabled aria-disabled="true">
					</form>
				 </td>
			   </tr>
			  </tbody>
			  {% endfor %}
		  </table>
	</div>
	<!-- Main Content End -->

app/templates/error.html
{% extends "generic.html" %}

{% load static %}

{% block content %}


<!-- Main Content Start -->
    <div class="container mt-5">
        <div class="alert alert-danger">
            <h2 class="alert-heading">La descarga no se pudo completar.</h2>
            <p>
                Intentelo de nuevo pinchando <a href="{% url 'ytdownloader:home' %}" class="alert-link">aquí.</a>
            </p>
      </div>
        <p>Si tiene algún problema puede consultar en la ventana de Contacto.</p>
    </div>
<!-- Main Content End -->

{% endblock %}

app/templates/finish.html
{% extends "generic.html" %}

{% load static %}

{% block content %}

<!-- Main Content Start -->
<div class="container mt-5">
    <div class="alert alert-success">
        <h2 class="alert-heading">La descarga finalizó con exíto.</h2>
        <p>
        Puede regresar al inicio pinchando <a href="{% url 'ytdownloader:home' %}" class="alert-link">aquí.</a>
        </p>
    </div>
        <p>Si no encuentra el video descargado , busque en su carpeta de descargas.</p>
        <p>Si usa frecuentemente la aplicación y le fue de ayuda considere donar.</p>
        <p>Si tiene alguna duda puede consultar en la ventana de Contacto.</p>
</div>
<!-- Main Content End -->
 
{% endblock %}

app/templates/generic.html
<!doctype html>
<html lang="es">
  <head>
    {% load static %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <!-- Fontawesome -->
    <script src="https://kit.fontawesome.com/5a300f8a6c.js" crossorigin="anonymous"></script>
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body>

    <!-- Start Navbar -->
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="http://francoding.pythonanywhere.com/"><img class="logo__img" src="https://bl3302files.storage.live.com/y4mZgAa1iKc3Yl7g7e5fAWsG0eoZt5JowXmlzrz2J6-M8zrTaG-Hc6kSeIVpxcohcq4Xvu7u9Q5tBMlorrP26PGVxlj3mCRFLMVzOV9EwqULeCeslrHwaVDWoqBYgTlHV6XWH2Oyd8JhgH2HZQeAwQZTJap109h2VhNTgIbiOSAPtTHnB1Pf1Ew-FIe7W3_Lsqi?width=250&height=100&cropmode=none"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ms-auto">
                <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page" href="{% url 'ytdownloader:home' %}">Descargar</a>
                <a class="nav-link {% if request.path == '/donations/' %}active{% endif %}" href="{% url 'ytdownloader:donations' %}">Donaciones</a>
                <a class="nav-link {% if request.path == '/contact/' %}active{% endif %}" href="{% url 'ytdownloader:contact' %}">Contacto</a>
            </div>
        </div>
      </div>
    </nav>

    <!-- End Navbar -->

    <!-- Inherit PLACE HERE -->

    {% block content %}

    {% endblock %}


    <!-- Footer start-->

<footer class="text-center bg-dark mt-5">
  <!-- Grid container -->
  <div class="container pt-4">
    <!-- Section: Social media -->
    <section class="mb-4">

      <!-- Instagram -->
      <a
        class="btn btn-link btn-floating btn-lg text-white m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-link btn-floating btn-lg text-white m-1"
        href="#!"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-link btn-floating btn-lg text-white m-1"
        href="https://github.com/frankto5"
        role="button"
        data-mdb-ripple-color="dark"
        ><i class="fab fa-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2021 Copyright:
    <a class="text-white" href="http://francoding.pythonanywhere.com/">YTUD.io</a>
  </div>
  <!-- Copyright -->
</footer>
    <!-- Footer end -->

    <!-- Popper and Bootstrap JS -->

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>

  </body>
</html>

app/templates/index.html
{% extends "generic.html" %}

{% load static %}

{% block content %}


<!-- Input and Download Button -->

<div class="container  mt-5">
 	<h2 class="my-5 text-center">Esta es una app en un servidor de prueba , no es funcional.</h2>
 		<form class="input-group" action="download/">
			<input name="url" type="text" class="form-control" placeholder="Link del video" aria-label="link" aria-describedby="button-addon2">
  			<button class="btn btn-outline-success" type="submit" id="button-addon2">Descargar</button>
		</form>
</div>

<!-- End Input and Download Button -->

<!-- Help start -->
<div class="container mt-5">
    <ol class="list-group list-group-numbered">
 		<li class="list-group-item">Elige tu video a descargar de YouTube y procede a pegar el link en el cuadro de texto indicado.</li>
  		<li class="list-group-item">Una vez has pegado el link en el cuadro de texto presiona en descargar para continuar.</li>
  		<li class="list-group-item">En la ventana de descargas asegúrate de elegir el formato correcto
		, MP3 (solo audio) y MP4 (audio y video).</li>
	</ol>
</div>
<!-- Help end -->

{% endblock %}

app/templates/thanks.html
{% extends "generic.html" %}

{% load static %}

{% block content %}

<!-- Main Content Start -->
<div class="container mt-5">
    <div class="alert alert-success">
        <h2 class="alert-heading">El mensaje fue enviado con éxito.</h2>
        <p>
        Gracias por contactarnos, puede regresar al inicio pinchando <a href="{% url 'ytdownloader:home' %}" class="alert-link">aquí.</a>
        </p>
    </div>
</div>
<!-- Main Content End -->

{% endblock %}